import {
  JWT_ACCESS_PRIVATE_KEY_NAME,
  JWT_ACCESS_PUBLIC_KEY_NAME,
  JWT_REFRESH_PRIVATE_KEY_NAME,
  JWT_REFRESH_PUBLIC_KEY_NAME,
} from "@/src/constants/jwt.constants.ts";

export const ENVIRONMENT = {
  applicationHostPort: "APPLICATION_HOST_PORT",
  [JWT_ACCESS_PRIVATE_KEY_NAME]: "JWT_ACCESS_PRIVATE_KEY",
  [JWT_ACCESS_PUBLIC_KEY_NAME]: "JWT_ACCESS_PUBLIC_KEY",
  [JWT_REFRESH_PRIVATE_KEY_NAME]: "JWT_REFRESH_PRIVATE_KEY",
  [JWT_REFRESH_PUBLIC_KEY_NAME]: "JWT_REFRESH_PUBLIC_KEY",
  mongoUri: "MONGO_URI",
  port: "PORT",
  resendApiKey: "RESEND_API_KEY",
} as const;
