name: Common Workflow Setup

# This workflow can be called from other workflows.
on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
        description: 'Node.js version to use (e.g., "20" or "lts/*")'
        default: "lts/*"
      pnpm_version:
        required: true
        type: string
        description: 'PNPM version to use (e.g., "10.x" or "latest")'
        default: "latest"
    outputs:
      pnpm_lock_hash:
        description: "SHA256 hash of pnpm-lock.yaml for cache key"
        value: ${{ jobs.setup.outputs.pnpm_lock_hash }}
      node_modules_artifact_name:
        description: "Name of the uploaded node_modules artifact"
        value: ${{ jobs.setup.outputs.node_modules_artifact_name }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      pnpm_lock_hash: ${{ steps.hash-lockfile.outputs.pnpm_lock_hash }}
      node_modules_artifact_name: ${{ steps.upload-node-modules.outputs.artifact_name }}
    steps:
      - name: "☁️ Checkout Repository"
        uses: actions/checkout@v4

      - name: "🔧 Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: "Setup PNPM"
        uses: pnpm/action-setup@v4
        with:
          version: ${{ inputs.pnpm_version }}

      - name: "🔍 Hash pnpm-lock.yaml for artifact key"
        id: hash-lockfile # Add an ID to this step to reference its outputs
        run: |
          # Use sha256sum to hash the lockfile
          echo "pnpm_lock_hash=$(sha256sum pnpm-lock.yaml | awk '{print $1}')" >> "$GITHUB_OUTPUT"
        working-directory: .

      - name: "🔧 Install Monorepo Dependencies"
        run: pnpm install --frozen-lockfile
        working-directory: .

      - name: "📦 Upload node_modules as artifact"
        id: upload-node-modules # Add an ID to this step to reference its outputs
        uses: actions/upload-artifact@v4
        with:
          name: node-modules-${{ runner.os }}-${{ steps.hash-lockfile.outputs.pnpm_lock_hash }}
          path: node_modules # Path to the root node_modules
          retention-days: 5
