/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as TermsRouteImport } from './app/routes/terms'
import { Route as PrivacyRouteImport } from './app/routes/privacy'
import { Route as LoginRouteImport } from './app/routes/login'
import { Route as ImprintRouteImport } from './app/routes/imprint'
import { Route as ResetPasswordRouteRouteImport } from './app/routes/reset-password/route'
import { Route as ResendVerificationMailRouteRouteImport } from './app/routes/resend-verification-mail/route'
import { Route as RegisterRouteRouteImport } from './app/routes/register/route'
import { Route as ForgotPasswordRouteRouteImport } from './app/routes/forgot-password/route'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as ResetPasswordIndexRouteImport } from './app/routes/reset-password/index'
import { Route as ResendVerificationMailIndexRouteImport } from './app/routes/resend-verification-mail/index'
import { Route as RegisterIndexRouteImport } from './app/routes/register/index'
import { Route as ForgotPasswordIndexRouteImport } from './app/routes/forgot-password/index'
import { Route as ResetPasswordSentRouteImport } from './app/routes/reset-password/sent'
import { Route as ResendVerificationMailSentRouteImport } from './app/routes/resend-verification-mail/sent'
import { Route as RegisterSuccessRouteImport } from './app/routes/register/success'
import { Route as ForgotPasswordSentRouteImport } from './app/routes/forgot-password/sent'
import { Route as ResetPasswordIdPasswordResetCodeIndexRouteImport } from './app/routes/reset-password/$id/$passwordResetCode/index'
import { Route as RegisterVerifyIdVerificationCodeIndexRouteImport } from './app/routes/register/verify/$id/$verificationCode/index'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRouteRoute = ResetPasswordRouteRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResendVerificationMailRouteRoute =
  ResendVerificationMailRouteRouteImport.update({
    id: '/resend-verification-mail',
    path: '/resend-verification-mail',
    getParentRoute: () => rootRouteImport,
  } as any)
const RegisterRouteRoute = RegisterRouteRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRouteRoute = ForgotPasswordRouteRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordIndexRoute = ResetPasswordIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResetPasswordRouteRoute,
} as any)
const ResendVerificationMailIndexRoute =
  ResendVerificationMailIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ResendVerificationMailRouteRoute,
  } as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegisterRouteRoute,
} as any)
const ForgotPasswordIndexRoute = ForgotPasswordIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ForgotPasswordRouteRoute,
} as any)
const ResetPasswordSentRoute = ResetPasswordSentRouteImport.update({
  id: '/sent',
  path: '/sent',
  getParentRoute: () => ResetPasswordRouteRoute,
} as any)
const ResendVerificationMailSentRoute =
  ResendVerificationMailSentRouteImport.update({
    id: '/sent',
    path: '/sent',
    getParentRoute: () => ResendVerificationMailRouteRoute,
  } as any)
const RegisterSuccessRoute = RegisterSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => RegisterRouteRoute,
} as any)
const ForgotPasswordSentRoute = ForgotPasswordSentRouteImport.update({
  id: '/sent',
  path: '/sent',
  getParentRoute: () => ForgotPasswordRouteRoute,
} as any)
const ResetPasswordIdPasswordResetCodeIndexRoute =
  ResetPasswordIdPasswordResetCodeIndexRouteImport.update({
    id: '/$id/$passwordResetCode/',
    path: '/$id/$passwordResetCode/',
    getParentRoute: () => ResetPasswordRouteRoute,
  } as any)
const RegisterVerifyIdVerificationCodeIndexRoute =
  RegisterVerifyIdVerificationCodeIndexRouteImport.update({
    id: '/verify/$id/$verificationCode/',
    path: '/verify/$id/$verificationCode/',
    getParentRoute: () => RegisterRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRouteRouteWithChildren
  '/register': typeof RegisterRouteRouteWithChildren
  '/resend-verification-mail': typeof ResendVerificationMailRouteRouteWithChildren
  '/reset-password': typeof ResetPasswordRouteRouteWithChildren
  '/imprint': typeof ImprintRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/forgot-password/sent': typeof ForgotPasswordSentRoute
  '/register/success': typeof RegisterSuccessRoute
  '/resend-verification-mail/sent': typeof ResendVerificationMailSentRoute
  '/reset-password/sent': typeof ResetPasswordSentRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/resend-verification-mail/': typeof ResendVerificationMailIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/reset-password/$id/$passwordResetCode': typeof ResetPasswordIdPasswordResetCodeIndexRoute
  '/register/verify/$id/$verificationCode': typeof RegisterVerifyIdVerificationCodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/imprint': typeof ImprintRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/forgot-password/sent': typeof ForgotPasswordSentRoute
  '/register/success': typeof RegisterSuccessRoute
  '/resend-verification-mail/sent': typeof ResendVerificationMailSentRoute
  '/reset-password/sent': typeof ResetPasswordSentRoute
  '/forgot-password': typeof ForgotPasswordIndexRoute
  '/register': typeof RegisterIndexRoute
  '/resend-verification-mail': typeof ResendVerificationMailIndexRoute
  '/reset-password': typeof ResetPasswordIndexRoute
  '/reset-password/$id/$passwordResetCode': typeof ResetPasswordIdPasswordResetCodeIndexRoute
  '/register/verify/$id/$verificationCode': typeof RegisterVerifyIdVerificationCodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRouteRouteWithChildren
  '/register': typeof RegisterRouteRouteWithChildren
  '/resend-verification-mail': typeof ResendVerificationMailRouteRouteWithChildren
  '/reset-password': typeof ResetPasswordRouteRouteWithChildren
  '/imprint': typeof ImprintRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/forgot-password/sent': typeof ForgotPasswordSentRoute
  '/register/success': typeof RegisterSuccessRoute
  '/resend-verification-mail/sent': typeof ResendVerificationMailSentRoute
  '/reset-password/sent': typeof ResetPasswordSentRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/resend-verification-mail/': typeof ResendVerificationMailIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/reset-password/$id/$passwordResetCode/': typeof ResetPasswordIdPasswordResetCodeIndexRoute
  '/register/verify/$id/$verificationCode/': typeof RegisterVerifyIdVerificationCodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/register'
    | '/resend-verification-mail'
    | '/reset-password'
    | '/imprint'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/forgot-password/sent'
    | '/register/success'
    | '/resend-verification-mail/sent'
    | '/reset-password/sent'
    | '/forgot-password/'
    | '/register/'
    | '/resend-verification-mail/'
    | '/reset-password/'
    | '/reset-password/$id/$passwordResetCode'
    | '/register/verify/$id/$verificationCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/imprint'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/forgot-password/sent'
    | '/register/success'
    | '/resend-verification-mail/sent'
    | '/reset-password/sent'
    | '/forgot-password'
    | '/register'
    | '/resend-verification-mail'
    | '/reset-password'
    | '/reset-password/$id/$passwordResetCode'
    | '/register/verify/$id/$verificationCode'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/register'
    | '/resend-verification-mail'
    | '/reset-password'
    | '/imprint'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/forgot-password/sent'
    | '/register/success'
    | '/resend-verification-mail/sent'
    | '/reset-password/sent'
    | '/forgot-password/'
    | '/register/'
    | '/resend-verification-mail/'
    | '/reset-password/'
    | '/reset-password/$id/$passwordResetCode/'
    | '/register/verify/$id/$verificationCode/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRouteRoute: typeof ForgotPasswordRouteRouteWithChildren
  RegisterRouteRoute: typeof RegisterRouteRouteWithChildren
  ResendVerificationMailRouteRoute: typeof ResendVerificationMailRouteRouteWithChildren
  ResetPasswordRouteRoute: typeof ResetPasswordRouteRouteWithChildren
  ImprintRoute: typeof ImprintRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resend-verification-mail': {
      id: '/resend-verification-mail'
      path: '/resend-verification-mail'
      fullPath: '/resend-verification-mail'
      preLoaderRoute: typeof ResendVerificationMailRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/': {
      id: '/reset-password/'
      path: '/'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof ResetPasswordIndexRouteImport
      parentRoute: typeof ResetPasswordRouteRoute
    }
    '/resend-verification-mail/': {
      id: '/resend-verification-mail/'
      path: '/'
      fullPath: '/resend-verification-mail/'
      preLoaderRoute: typeof ResendVerificationMailIndexRouteImport
      parentRoute: typeof ResendVerificationMailRouteRoute
    }
    '/register/': {
      id: '/register/'
      path: '/'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof RegisterRouteRoute
    }
    '/forgot-password/': {
      id: '/forgot-password/'
      path: '/'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof ForgotPasswordIndexRouteImport
      parentRoute: typeof ForgotPasswordRouteRoute
    }
    '/reset-password/sent': {
      id: '/reset-password/sent'
      path: '/sent'
      fullPath: '/reset-password/sent'
      preLoaderRoute: typeof ResetPasswordSentRouteImport
      parentRoute: typeof ResetPasswordRouteRoute
    }
    '/resend-verification-mail/sent': {
      id: '/resend-verification-mail/sent'
      path: '/sent'
      fullPath: '/resend-verification-mail/sent'
      preLoaderRoute: typeof ResendVerificationMailSentRouteImport
      parentRoute: typeof ResendVerificationMailRouteRoute
    }
    '/register/success': {
      id: '/register/success'
      path: '/success'
      fullPath: '/register/success'
      preLoaderRoute: typeof RegisterSuccessRouteImport
      parentRoute: typeof RegisterRouteRoute
    }
    '/forgot-password/sent': {
      id: '/forgot-password/sent'
      path: '/sent'
      fullPath: '/forgot-password/sent'
      preLoaderRoute: typeof ForgotPasswordSentRouteImport
      parentRoute: typeof ForgotPasswordRouteRoute
    }
    '/reset-password/$id/$passwordResetCode/': {
      id: '/reset-password/$id/$passwordResetCode/'
      path: '/$id/$passwordResetCode'
      fullPath: '/reset-password/$id/$passwordResetCode'
      preLoaderRoute: typeof ResetPasswordIdPasswordResetCodeIndexRouteImport
      parentRoute: typeof ResetPasswordRouteRoute
    }
    '/register/verify/$id/$verificationCode/': {
      id: '/register/verify/$id/$verificationCode/'
      path: '/verify/$id/$verificationCode'
      fullPath: '/register/verify/$id/$verificationCode'
      preLoaderRoute: typeof RegisterVerifyIdVerificationCodeIndexRouteImport
      parentRoute: typeof RegisterRouteRoute
    }
  }
}

interface ForgotPasswordRouteRouteChildren {
  ForgotPasswordSentRoute: typeof ForgotPasswordSentRoute
  ForgotPasswordIndexRoute: typeof ForgotPasswordIndexRoute
}

const ForgotPasswordRouteRouteChildren: ForgotPasswordRouteRouteChildren = {
  ForgotPasswordSentRoute: ForgotPasswordSentRoute,
  ForgotPasswordIndexRoute: ForgotPasswordIndexRoute,
}

const ForgotPasswordRouteRouteWithChildren =
  ForgotPasswordRouteRoute._addFileChildren(ForgotPasswordRouteRouteChildren)

interface RegisterRouteRouteChildren {
  RegisterSuccessRoute: typeof RegisterSuccessRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  RegisterVerifyIdVerificationCodeIndexRoute: typeof RegisterVerifyIdVerificationCodeIndexRoute
}

const RegisterRouteRouteChildren: RegisterRouteRouteChildren = {
  RegisterSuccessRoute: RegisterSuccessRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  RegisterVerifyIdVerificationCodeIndexRoute:
    RegisterVerifyIdVerificationCodeIndexRoute,
}

const RegisterRouteRouteWithChildren = RegisterRouteRoute._addFileChildren(
  RegisterRouteRouteChildren,
)

interface ResendVerificationMailRouteRouteChildren {
  ResendVerificationMailSentRoute: typeof ResendVerificationMailSentRoute
  ResendVerificationMailIndexRoute: typeof ResendVerificationMailIndexRoute
}

const ResendVerificationMailRouteRouteChildren: ResendVerificationMailRouteRouteChildren =
  {
    ResendVerificationMailSentRoute: ResendVerificationMailSentRoute,
    ResendVerificationMailIndexRoute: ResendVerificationMailIndexRoute,
  }

const ResendVerificationMailRouteRouteWithChildren =
  ResendVerificationMailRouteRoute._addFileChildren(
    ResendVerificationMailRouteRouteChildren,
  )

interface ResetPasswordRouteRouteChildren {
  ResetPasswordSentRoute: typeof ResetPasswordSentRoute
  ResetPasswordIndexRoute: typeof ResetPasswordIndexRoute
  ResetPasswordIdPasswordResetCodeIndexRoute: typeof ResetPasswordIdPasswordResetCodeIndexRoute
}

const ResetPasswordRouteRouteChildren: ResetPasswordRouteRouteChildren = {
  ResetPasswordSentRoute: ResetPasswordSentRoute,
  ResetPasswordIndexRoute: ResetPasswordIndexRoute,
  ResetPasswordIdPasswordResetCodeIndexRoute:
    ResetPasswordIdPasswordResetCodeIndexRoute,
}

const ResetPasswordRouteRouteWithChildren =
  ResetPasswordRouteRoute._addFileChildren(ResetPasswordRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRouteRoute: ForgotPasswordRouteRouteWithChildren,
  RegisterRouteRoute: RegisterRouteRouteWithChildren,
  ResendVerificationMailRouteRoute:
    ResendVerificationMailRouteRouteWithChildren,
  ResetPasswordRouteRoute: ResetPasswordRouteRouteWithChildren,
  ImprintRoute: ImprintRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
