/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as TermsRouteImport } from './app/routes/terms'
import { Route as RegisterSuccessRouteImport } from './app/routes/register-success'
import { Route as RegisterRouteImport } from './app/routes/register'
import { Route as PrivacyRouteImport } from './app/routes/privacy'
import { Route as LoginRouteImport } from './app/routes/login'
import { Route as ImprintRouteImport } from './app/routes/imprint'
import { Route as EmailVerifiedRouteImport } from './app/routes/email-verified'
import { Route as ResetPasswordRouteRouteImport } from './app/routes/reset-password/route'
import { Route as ForgotPasswordRouteRouteImport } from './app/routes/forgot-password/route'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as ResetPasswordIndexRouteImport } from './app/routes/reset-password/index'
import { Route as ForgotPasswordIndexRouteImport } from './app/routes/forgot-password/index'
import { Route as ResetPasswordSentRouteImport } from './app/routes/reset-password/sent'
import { Route as ForgotPasswordSentRouteImport } from './app/routes/forgot-password/sent'
import { Route as ResetPasswordIdPasswordResetCodeIndexRouteImport } from './app/routes/reset-password/$id/$passwordResetCode/index'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterSuccessRoute = RegisterSuccessRouteImport.update({
  id: '/register-success',
  path: '/register-success',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailVerifiedRoute = EmailVerifiedRouteImport.update({
  id: '/email-verified',
  path: '/email-verified',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRouteRoute = ResetPasswordRouteRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRouteRoute = ForgotPasswordRouteRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordIndexRoute = ResetPasswordIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResetPasswordRouteRoute,
} as any)
const ForgotPasswordIndexRoute = ForgotPasswordIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ForgotPasswordRouteRoute,
} as any)
const ResetPasswordSentRoute = ResetPasswordSentRouteImport.update({
  id: '/sent',
  path: '/sent',
  getParentRoute: () => ResetPasswordRouteRoute,
} as any)
const ForgotPasswordSentRoute = ForgotPasswordSentRouteImport.update({
  id: '/sent',
  path: '/sent',
  getParentRoute: () => ForgotPasswordRouteRoute,
} as any)
const ResetPasswordIdPasswordResetCodeIndexRoute =
  ResetPasswordIdPasswordResetCodeIndexRouteImport.update({
    id: '/$id/$passwordResetCode/',
    path: '/$id/$passwordResetCode/',
    getParentRoute: () => ResetPasswordRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRouteRouteWithChildren
  '/reset-password': typeof ResetPasswordRouteRouteWithChildren
  '/email-verified': typeof EmailVerifiedRoute
  '/imprint': typeof ImprintRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/register-success': typeof RegisterSuccessRoute
  '/terms': typeof TermsRoute
  '/forgot-password/sent': typeof ForgotPasswordSentRoute
  '/reset-password/sent': typeof ResetPasswordSentRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/reset-password/$id/$passwordResetCode': typeof ResetPasswordIdPasswordResetCodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/email-verified': typeof EmailVerifiedRoute
  '/imprint': typeof ImprintRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/register-success': typeof RegisterSuccessRoute
  '/terms': typeof TermsRoute
  '/forgot-password/sent': typeof ForgotPasswordSentRoute
  '/reset-password/sent': typeof ResetPasswordSentRoute
  '/forgot-password': typeof ForgotPasswordIndexRoute
  '/reset-password': typeof ResetPasswordIndexRoute
  '/reset-password/$id/$passwordResetCode': typeof ResetPasswordIdPasswordResetCodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRouteRouteWithChildren
  '/reset-password': typeof ResetPasswordRouteRouteWithChildren
  '/email-verified': typeof EmailVerifiedRoute
  '/imprint': typeof ImprintRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/register-success': typeof RegisterSuccessRoute
  '/terms': typeof TermsRoute
  '/forgot-password/sent': typeof ForgotPasswordSentRoute
  '/reset-password/sent': typeof ResetPasswordSentRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/reset-password/$id/$passwordResetCode/': typeof ResetPasswordIdPasswordResetCodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/email-verified'
    | '/imprint'
    | '/login'
    | '/privacy'
    | '/register'
    | '/register-success'
    | '/terms'
    | '/forgot-password/sent'
    | '/reset-password/sent'
    | '/forgot-password/'
    | '/reset-password/'
    | '/reset-password/$id/$passwordResetCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/email-verified'
    | '/imprint'
    | '/login'
    | '/privacy'
    | '/register'
    | '/register-success'
    | '/terms'
    | '/forgot-password/sent'
    | '/reset-password/sent'
    | '/forgot-password'
    | '/reset-password'
    | '/reset-password/$id/$passwordResetCode'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/email-verified'
    | '/imprint'
    | '/login'
    | '/privacy'
    | '/register'
    | '/register-success'
    | '/terms'
    | '/forgot-password/sent'
    | '/reset-password/sent'
    | '/forgot-password/'
    | '/reset-password/'
    | '/reset-password/$id/$passwordResetCode/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRouteRoute: typeof ForgotPasswordRouteRouteWithChildren
  ResetPasswordRouteRoute: typeof ResetPasswordRouteRouteWithChildren
  EmailVerifiedRoute: typeof EmailVerifiedRoute
  ImprintRoute: typeof ImprintRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  RegisterSuccessRoute: typeof RegisterSuccessRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-success': {
      id: '/register-success'
      path: '/register-success'
      fullPath: '/register-success'
      preLoaderRoute: typeof RegisterSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-verified': {
      id: '/email-verified'
      path: '/email-verified'
      fullPath: '/email-verified'
      preLoaderRoute: typeof EmailVerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/': {
      id: '/reset-password/'
      path: '/'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof ResetPasswordIndexRouteImport
      parentRoute: typeof ResetPasswordRouteRoute
    }
    '/forgot-password/': {
      id: '/forgot-password/'
      path: '/'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof ForgotPasswordIndexRouteImport
      parentRoute: typeof ForgotPasswordRouteRoute
    }
    '/reset-password/sent': {
      id: '/reset-password/sent'
      path: '/sent'
      fullPath: '/reset-password/sent'
      preLoaderRoute: typeof ResetPasswordSentRouteImport
      parentRoute: typeof ResetPasswordRouteRoute
    }
    '/forgot-password/sent': {
      id: '/forgot-password/sent'
      path: '/sent'
      fullPath: '/forgot-password/sent'
      preLoaderRoute: typeof ForgotPasswordSentRouteImport
      parentRoute: typeof ForgotPasswordRouteRoute
    }
    '/reset-password/$id/$passwordResetCode/': {
      id: '/reset-password/$id/$passwordResetCode/'
      path: '/$id/$passwordResetCode'
      fullPath: '/reset-password/$id/$passwordResetCode'
      preLoaderRoute: typeof ResetPasswordIdPasswordResetCodeIndexRouteImport
      parentRoute: typeof ResetPasswordRouteRoute
    }
  }
}

interface ForgotPasswordRouteRouteChildren {
  ForgotPasswordSentRoute: typeof ForgotPasswordSentRoute
  ForgotPasswordIndexRoute: typeof ForgotPasswordIndexRoute
}

const ForgotPasswordRouteRouteChildren: ForgotPasswordRouteRouteChildren = {
  ForgotPasswordSentRoute: ForgotPasswordSentRoute,
  ForgotPasswordIndexRoute: ForgotPasswordIndexRoute,
}

const ForgotPasswordRouteRouteWithChildren =
  ForgotPasswordRouteRoute._addFileChildren(ForgotPasswordRouteRouteChildren)

interface ResetPasswordRouteRouteChildren {
  ResetPasswordSentRoute: typeof ResetPasswordSentRoute
  ResetPasswordIndexRoute: typeof ResetPasswordIndexRoute
  ResetPasswordIdPasswordResetCodeIndexRoute: typeof ResetPasswordIdPasswordResetCodeIndexRoute
}

const ResetPasswordRouteRouteChildren: ResetPasswordRouteRouteChildren = {
  ResetPasswordSentRoute: ResetPasswordSentRoute,
  ResetPasswordIndexRoute: ResetPasswordIndexRoute,
  ResetPasswordIdPasswordResetCodeIndexRoute:
    ResetPasswordIdPasswordResetCodeIndexRoute,
}

const ResetPasswordRouteRouteWithChildren =
  ResetPasswordRouteRoute._addFileChildren(ResetPasswordRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRouteRoute: ForgotPasswordRouteRouteWithChildren,
  ResetPasswordRouteRoute: ResetPasswordRouteRouteWithChildren,
  EmailVerifiedRoute: EmailVerifiedRoute,
  ImprintRoute: ImprintRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  RegisterSuccessRoute: RegisterSuccessRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
