name: "Setup Monorepo"
description: "Sets up Node.js, pnpm, installs dependencies, and builds all packages"
inputs:
  node_version:
    description: "Node.js version to use"
    required: false
    default: "lts/*"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Build all packages
      shell: bash
      run: pnpm build
